---
- name: Configure Debian Environment
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'
    and 'microsoft' not in ansible_kernel | lower
    and 'wsl' not in ansible_kernel | lower
