---
- name: "Install nginx"
  apt: 
    pkg:
      - nginx
    state: latest
    force: yes
    update_cache: yes

- name: "Disable default config"
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: "Restart and enable nginx"
  service:
    name: nginx
    state: restarted
    enabled: yes
