---
- name: Install key for sublime text
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add sublime repo
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    update_cache: yes

- name: Install sublime text and sublime merge
  apt:
    pkg:
      - sublime-text
      - sublime-merge
    state: present
    force: yes
