---
- name: Install key for sublime text
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /etc/apt/trusted.gpg.d/sublimehq.gpg
    state: present

- name: Add sublime repo
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    update_cache: yes

- name: Install sublime text and sublime merge
  become: yes
  apt:
    pkg:
      - sublime-text
      - sublime-merge
    state: present
    force: yes

- name: Ensures sublime-text directory exists
  file:
    path: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Add custom settings to sublime text
  copy:
    src: files/Preferences.sublime-settings
    dest: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Add custom keymap to sublime text
  copy:
    src: files/Default (Linux).sublime-keymap
    dest: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
