---
- name: Install key for sublime text
  become: true
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /etc/apt/trusted.gpg.d/sublimehq.gpg
    state: present

- name: Add sublime repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    update_cache: true

- name: Install sublime text and sublime merge
  become: true
  ansible.builtin.apt:
    pkg:
      - sublime-text
      - sublime-merge
    state: present
    force: true

- name: Ensures sublime-text directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0650"
    state: directory

- name: Add custom settings to sublime text
  ansible.builtin.copy:
    src: files/Preferences.sublime-settings
    dest: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Add custom keymap to sublime text
  ansible.builtin.copy:
    src: files/Default (Linux).sublime-keymap
    dest: /home/{{ ansible_user }}/.config/sublime-text/Packages/User
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
