---
- name: Install common dependencies
  become: yes
  apt:
    pkg:
      - git
      - curl
      - wget
      - zip
      - unzip
      - net-tools
      - network-manager
      - libnss3-tools
      - jq
      - xsel
    state: present
    force: yes
    update_cache: yes
