---
- name: Install common dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      "{{ item }}"
    state: present
    force: true
    update_cache: true
  with_items:
    - git
    - curl
    - wget
    - zip
    - unzip
    - net-tools
    - network-manager
    - libnss3-tools
    - jq
    - xsel
