---
- name: Add nodejs apt key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodejs.gpg
    state: present

- name: Add nodejs ppa
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x focal main
    update_cache: yes

- name: Install nodejs
  become: yes
  apt: 
    pkg: nodejs
    state: present
    update_cache: yes

- name: Create npm's directory
  become_user: "{{ ansible_user }}"
  become: yes
  file:
    path: "/home/{{ ansible_user }}/.npm-global"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0774
    state: directory

- name: Change npm's default directory
  become_user: "{{ ansible_user }}"
  become: yes
  shell: |
    npm config set prefix '~/.npm-global'
    echo export PATH=~/.npm-global/bin:$PATH > ~/.profile
