---
- name: "Install zsh and dependencies"
  apt:
    pkg:
      - zsh
      - fonts-powerline
    state: present
    force: yes

- name: "Check that .oh-my-zsh is installed"
  stat:
    path: /home/{{ username }}/.oh-my-zsh
  register: ohmyzsh_installed

- name: "Download zsh"
  get_url: 
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: /tmp/zsh-installer.sh
    owner: "{{ username }}"
    group: "{{ username }}"
  when: ohmyzsh_installed.stat.exists == False

- name: "Install zsh"
  become: yes
  become_user: "{{ username }}"
  shell: "sh /tmp/zsh-installer.sh"
  when: ohmyzsh_installed.stat.exists == False

- name: "Remove zsh-installer.sh"
  become: yes
  become_user: "{{ username }}"
  file: path=/tmp/zsh-installer.sh state=absent
  when: ohmyzsh_installed.stat.exists == False

- name: "Replace .zshrc file"
  copy:
    src: files/.zshrc
    dest: /home/{{ username }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  when: ohmyzsh_installed.stat.exists == False

- name: "Change shell to zsh"
  shell: "chsh -s /usr/bin/zsh {{ username }}"
