---
- name: Add php ondrej apt repository
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install php
  become: yes
  apt:
    pkg:
      php8.1-fpm
    state: present
    force: yes
    update_cache: yes

- name: Install php dependencies
  become: yes
  apt:
    pkg:
      - php8.1
      - php8.1-mysql
      - php8.1-curl
      - php8.1-gd
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-soap
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-zip
    state: present
    force: yes
    update_cache: yes
