---
- name: Install nginx
  become: yes
  apt: 
    pkg:
      - nginx
    state: latest
    force: yes
    update_cache: yes

- name: Disable default config
  become: yes
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart and enable nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
