---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    pkg:
      - nginx
    state: present
    force: true
    update_cache: true

- name: Disable default config
  become: true
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart and enable nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
