---
- name: Install nginx
  apt: 
    pkg:
      - nginx
    state: latest
    force: yes
    update_cache: yes
  notify:
    - Start Nginx

- name: Disable default config
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload Nginx
