---
- name: Install zsh and dependencies
  apt:
    pkg:
      - zsh
      - powerline
      - fonts-powerline
    state: present
    force: yes

- name: Check that .oh-my-zsh is installed
  stat:
    path: /home/{{ ansible_user }}/.oh-my-zsh
  register: ohmyzsh_installed

- name: Download zsh shell
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: ohmyzsh_installed.stat.exists == False

- name: Install zsh shell
  become: yes
  become_user: "{{ ansible_user }}"
  shell: sh /tmp/zsh-installer.sh
  when: ohmyzsh_installed.stat.exists == False

- name: Remove zsh-installer.sh
  become: yes
  become_user: "{{ ansible_user }}"
  file:
    path: /tmp/zsh-installer.sh
    state: absent
  when: ohmyzsh_installed.stat.exists == False

- name: Change shell to zsh
  shell: "chsh -s /usr/bin/zsh {{ ansible_user }}"

- name: Download Powerlevel10k Theme
  git:
    depth: 1
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k

- name: Replace .zshrc file
  copy:
    src: files/.zshrc
    dest: /home/{{ ansible_user }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
