---
- name: Check that composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_installed

- name: Download composer
  get_url: 
    url: "{{ composer_url }}"
    checksum: sha256:{{ composer_url }}.sha256sum
    dest: /tmp/composer.phar
    mode: 0755
  when: composer_installed.stat.exists == False

- name: Install composer
  shell: mv /tmp/composer.phar /usr/local/bin/composer
  when: composer_installed.stat.exists == False

- name: Replace .profile file
  copy: 
    src: files/.profile
    dest: /home/{{ username }}/.profile
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  when: composer_installed.stat.exists == False
