---
- name: Check that composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_installed

- name: Download composer
  get_url: 
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: "sha384:756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3"
  when: composer_installed.stat.exists == False

- name: Install composer
  shell: "php /tmp/composer-setup.php --install-dir=/usr/local/bin"
  when: composer_installed.stat.exists == False

- name: Rename composer.phar to composer
  shell: "mv /usr/local/bin/composer.phar /usr/local/bin/composer"
  when: composer_installed.stat.exists == False

- name: Remove composer-setup.phar
  file: 
    dest: /tmp/composer-setup.php
    state: absent
  when: composer_installed.stat.exists == False

- name: Replace .profile file
  copy: 
    src: files/.profile
    dest: /home/{{ username }}/.profile
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  when: composer_installed.stat.exists == False
