---
- name: Install mysql server
  become: true
  ansible.builtin.apt:
    pkg:
      - mysql-server
    state: present
    force: true
    update_cache: true

- name: Add my.cnf configuration
  become: true
  ansible.builtin.template:
    src: files/my.cnf
    dest: /etc/mysql/conf.d
    owner: root
    group: root
    mode: "0644"

- name: Restart and enable mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
