---
- name: Install mysql server
  become: true
  ansible.builtin.apt:
    pkg:
      "{{ item }}"
    state: present
    force: true
    update_cache: true
  with_items:
    - mysql-server-8.0
    - python3-pymysql

- name: Add my.cnf configuration
  become: true
  ansible.builtin.template:
    src: files/my.cnf
    dest: /etc/mysql/conf.d
    owner: root
    group: root
    mode: "0644"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Create mysql database
  become: true
  become_user: root
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present

- name: Create mysql user
  become: true
  become_user: root
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
