---
- name: Install mysql server
  become: true
  ansible.builtin.apt:
    pkg:
      "{{ item }}"
    state: present
    force: true
    update_cache: true
  with_items:
    - mysql-server-8.0
    - python3-pymysql

- name: Add my.cnf configuration
  become: true
  ansible.builtin.template:
    src: files/my.cnf
    dest: /etc/mysql/conf.d
    owner: root
    group: root
    mode: "0644"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
