---
- name: Copy backup of terminal settings
  copy: 
    src: files/gnome_terminal_settings_backup.txt
    dest: /tmp/gnome_terminal_settings_backup.txt
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Recovery backup of terminal settings
  become: yes
  become_user: "{{ username }}"
  shell: dconf load /org/gnome/terminal/ < /tmp/gnome_terminal_settings_backup.txt

- name: Remove backup of terminal settings
  file: 
    dest: /tmp/gnome_terminal_settings_backup.txt
    state: absent
