---
- name: Add php ondrej apt repository
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install php
  become: yes
  apt:
    pkg:
      php8.0-fpm
    state: present
    force: yes
    update_cache: yes

- name: Install php dependencies
  become: yes
  apt:
    pkg:
      - php8.0
      - php8.0-mysql
      - php8.0-curl
      - php8.0-gd
      - php8.0-intl
      - php8.0-mbstring
      - php8.0-soap
      - php8.0-xml
      - php8.0-xmlrpc
      - php8.0-zip
    state: present
    force: yes
    update_cache: yes
