---
- name: Provision laravel development
  hosts: localhost
  roles:
    - { role: common, tags: common }
    - { role: php, tags: php }
    - { role: composer, tags: composer }
    - { role: nginx, tags: nginx }
    - { role: nodejs, tags: nodejs }
    - { role: yarn, tags: yarn }
    - { role: mysql, tags: mysql }
    - { role: redis, tags: redis }
    - { role: supervisor, tags: supervisor }
    - { role: vscode, tags: vscode }
    - { role: laravel, tags: laravel }
    - { role: valet, tags: valet }
