---
- name: Provision laravel development
  hosts: localhost
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3.10
    php_version: 8.3
    npm_version: 20.12.2
    postgresql_version: 16
    db_user: laravel
    db_name: laravel
    db_password: password
  roles:
    - { role: common, tags: common }
    # - { role: fonts, tags: fonts } # TODO: resolve issue with zsh
    - { role: php, tags: php }
    - { role: composer, tags: composer }
    - { role: nginx, tags: nginx }
    - { role: nvm, tags: nvm }
    - { role: npm, tags: npm }
    - { role: mysql, tags: mysql }
    - { role: postgres, tags: postgres }
    - { role: redis, tags: redis }
    - { role: supervisor, tags: supervisor }
    - { role: sublime, tags: sublime }
    - { role: vscode, tags: vscode }
    # - { role: zsh, tags: zsh } # TODO: resolve issue with zsh
    # - { role: terminal, tags: terminal } # TODO: resolve issue with zsh
    - { role: laravel, tags: laravel }
    - { role: valet, tags: valet }
