---
- name: Provision laravel server
  hosts: laravel
  vars:
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3.10
    php_version: 8.3
    npm_version: 20.12.2
  roles:
    - { role: common, tags: common }
    - { role: php, tags: php }
    - { role: composer, tags: composer }
    - { role: nginx, tags: nginx }
    - { role: nvm, tags: nvm }
    - { role: npm, tags: npm }
    - { role: mysql, tags: mysql }
    - { role: redis, tags: redis }
    - { role: supervisor, tags: supervisor }
    - { role: valet, tags: valet }
    - { role: laravel, tags: laravel }
