---
- name: Check that valet is installed
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/.config/composer/vendor/bin/valet
  register: valet_installed

- name: Add valet to global composer
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: /usr/local/bin/composer global require cpriego/valet-linux
  when: not valet_installed.stat.exists
  changed_when: valet_installed.stat.exists

- name: Install valet
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: /home/{{ ansible_user }}/.config/composer/vendor/bin/valet install
  when: |
    not valet_installed.stat.exists
    and ansible_connection == 'local'
  changed_when: valet_installed.stat.exists
