---
- name: Create fonts direcitoy
  become: yes
  file:
    path: /home/{{ username }}/.fonts/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0774
    state: directory

- name: Copy fonts to system
  become: yes
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ username }}/.fonts/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664
  loop:
    - "MesloLGS NF Regular.ttf"
    - "MesloLGS NF Bold.ttf"
    - "MesloLGS NF Italic.ttf"
    - "MesloLGS NF Bold Italic.ttf"
